=== ggear/homeassistant-powercalc/profile_library/model_schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "model.json describes a number of devices, typically lights, for use within the HomeAssistant Powercalc extension.",
  "type": "object",
  "required": [
    "name",
    "device_type",
    "measure_method",
    "measure_device",
    "calculation_strategy",
    "created_at"
  ],
  "properties": {
    "aliases": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Aliases for this model"
    },
    "legacy_ids": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "Legacy canonical model ids which should migrate to this model"
    },
    "compatible_integrations": {
      "type": "array",
      "items": {
        "type": "string"
      },
      "description": "List of compatible integrations for this model"
    },
    "author": {
      "type": "string",
      "deprecated": true
    },
    "author_info": {
      "type": "object",
      "description": "Info about the contributor of the profile",
      "properties": {
        "name": {
          "type": "string",
          "description": "Name of the contributor"
        },
        "email": {
          "type": "string",
          "description": "Email address of the contributor"
        },
        "github": {
          "type": "string",
          "description": "GitHub username of the contributor"
        }
      },
      "required": [
        "name",
        "github"
      ]
    },
    "calculation_enabled_condition": {
      "type": "string",
      "description": "Template which can be evaluated."
    },
    "calculation_strategy": {
      "type": "string",
      "enum": [
        "lut",
        "linear",
        "fixed",
        "multi_switch",
        "composite"
      ],
      "description": "Supported calculation strategies"
    },
    "composite_config": {
      "oneOf": [
        {
          "type": "array",
          "description": "Configuration for composite calculation strategy",
          "items": {
            "type": "object",
            "properties": {
              "condition": {
                "$ref": "#/definitions/condition"
              }
            }
          }
        },
        {
          "type": "object",
          "properties": {
            "mode": {
              "type": "string",
              "enum": [
                "sum_all",
                "stop_at_first"
              ]
            },
            "strategies": {
              "type": "array",
              "description": "Configuration for composite calculation strategy",
              "items": {
                "type": "object",
                "properties": {
                  "condition": {
                    "$ref": "#/definitions/condition"
                  }
                }
              }
            }
          },
          "required": [
            "mode",
            "strategies"
          ]
        }
      ]
    },
    "config_flow_discovery_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on first step of discovery"
    },
    "config_flow_sub_profile_remarks": {
      "type": "string",
      "description": "Some remarks to show in the GUI config flow on sub profile selection step"
    },
    "created_at": {
      "type": "string",
      "format": "date-time",
      "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$",
      "description": "Creation date of the profile"
    },
    "description": {
      "type": "string",
      "description": "A short description of the device"
    },
    "device_type": {
      "type": "string",
      "enum": [
        "camera",
        "cover",
        "fan",
        "generic_iot",
        "light",
        "power_meter",
        "printer",
        "smart_dimmer",
        "smart_switch",
        "smart_speaker",
        "television",
        "network",
        "vacuum_robot",
        "lawn_mower_robot",
        "heating",
        "ups"
      ],
      "description": "Type of device"
    },
    "discovery_by": {
      "type": "string",
      "enum": [
        "device",
        "entity"
      ],
      "description": "Whether to discover the profile by device or entity"
    },
    "fields": {
      "type": "object",
      "additionalProperties": {
        "type": "object",
        "properties": {
          "description": {
            "type": "string",
            "description": "Description of the field"
          },
          "label": {
            "type": "string",
            "description": "Label of the field"
          },
          "selector": {
            "type": "object",
            "properties": {
              "entity": {
                "type": "object",
                "properties": {
                  "domain": {
                    "type": "string"
                  },
                  "device_class": {
                    "type": "string"
                  }
                }
              },
              "number": {
                "type": "object",
                "properties": {
                  "min": {
                    "type": "number"
                  },
                  "max": {
                    "type": "number"
                  }
                }
              }
            }
          }
        }
      }
    },
    "fixed_config": {
      "type": "object",
      "description": "Configuration for fixed calculation strategy",
      "properties": {
        "power": {
          "type": [
            "number",
            "string"
          ]
        },
        "states_power": {
          "type": "object",
          "description": "A dict of state attributes and the power. See https://github.com/bramstroker/homeassistant-powercalc#power-per-state.",
          "properties": {
            "idle": {
              "type": [
                "number",
                "string"
              ]
            },
            "playing": {
              "type": [
                "number",
                "string"
              ]
            },
            "paused": {
              "type": [
                "number",
                "string"
              ]
            },
            "off": {
              "type": [
                "number",
                "string"
              ]
            },
            "unavailable": {
              "type": [
                "number",
                "string"
              ]
            }
          },
          "additionalProperties": {
            "type": [
              "number",
              "string"
            ]
          }
        }
      }
    },
    "is_dumb_bulb": {
      "type": "boolean",
      "description": "The profile is for a dumb light bulb, not having smart capabilities"
    },
    "name": {
      "type": "string",
      "description": "The full name"
    },
    "measure_method": {
      "type": "string",
      "enum": [
        "manual",
        "script"
      ],
      "description": "How the device was measured"
    },
    "measure_description": {
      "type": "string",
      "description": "Add more information about how you measured the device or any remarks"
    },
    "measure_device": {
      "type": "string",
      "description": "Device which was used to measure"
    },
    "measure_device_firmware": {
      "type": "string",
      "description": "Firmware version of the device used to measure"
    },
    "measure_settings": {
      "type": "object",
      "description": "Settings used for measure script"
    },
    "min_version": {
      "type": "string",
      "description": "Minimum required version of Powercalc for this profile"
    },
    "linear_config": {
      "type": "object",
      "description": "Configuration for linear calculation strategy",
      "properties": {
        "min_power": {
          "type": "number"
        },
        "max_power": {
          "type": "number"
        },
        "calibrate": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "linked_lut": {
      "type": "string",
      "description": "Use LUT data files from another model",
      "deprecated": true
    },
    "linked_profile": {
      "type": "string",
      "description": "Use data from another model"
    },
    "only_self_usage": {
      "type": "boolean",
      "description": "Indicates if profile only provides power usage for the device itself"
    },
    "playbook_config": {
      "type": "object",
      "description": "Configuration for playbook calculation strategy",
      "properties": {
        "playbooks": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Key-value pairs where the key is a playbook ID and the value is the filename."
        },
        "autostart": {
          "type": "string",
          "description": "The playbook ID to autostart."
        },
        "repeat": {
          "type": "boolean",
          "description": "Indicates if the playbook should repeat."
        },
        "state_trigger": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Start given playbook when entity state changes to given value."
        }
      },
      "required": [
        "playbooks"
      ]
    },
    "sensor_config": {
      "type": "object",
      "description": "Sensor configuration options. See the README"
    },
    "standby_power": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned off. When you are not able to measure set to 0.4 for lights"
    },
    "standby_power_on": {
      "type": "number",
      "minimum": 0.05,
      "description": "Power draw when the device is turned on."
    },
    "sub_profile_select": {
      "type": "object",
      "description": "Configuration to automatically select a sub profile",
      "required": [
        "default"
      ],
      "properties": {
        "default": {
          "type": "string",
          "description": "Default profile to select when non of the matchers apply"
        },
        "matchers": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "enum": [
                  "attribute",
                  "entity_id",
                  "entity_state",
                  "integration",
                  "model_id"
                ]
              },
              "attribute": {
                "type": "string"
              },
              "map": {
                "type": "object"
              },
              "pattern": {
                "type": "string"
              },
              "profile": {
                "type": "string"
              },
              "integration": {
                "type": "string"
              },
              "model_id": {
                "type": "string"
              }
            },
            "required": [
              "type"
            ]
          },
          "description": "List of matchers which will be checked"
        }
      }
    }
  },
  "definitions": {
    "condition": {
      "type": "object",
      "properties": {
        "condition": {
          "type": "string",
          "enum": [
            "and",
            "or",
            "state",
            "numeric_state",
            "template"
          ]
        },
        "conditions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/condition"
          }
        }
      },
      "additionalProperties": true
    }
  }
}

=== ggear/homeassistant-powercalc/profile_library/ikea/E2491/model.json
{
  "aliases": [
    "4096"
  ],
  "calculation_strategy": "fixed",
  "created_at": "2026-04-18T23:21:36Z",
  "device_type": "smart_switch",
  "measure_description": "Manually measured with a dummy load attached at 25W (average over 600s) and 4 devices, than calculated average of that.",
  "measure_device": "Shelly PM Mini Gen3",
  "measure_method": "manual",
  "name": "GRILLPLATS Smart Plug (Matter)",
  "only_self_usage": true,
  "sensor_config": {
    "energy_sensor_naming": "{} Device Energy",
    "power_sensor_naming": "{} Device Power"
  },
  "standby_power": 0.22,
  "standby_power_on": 0.47,
  "author_info": {
    "name": "Tim",
    "github": "EinRainerZufall"
  }
}

=== ggear/homeassistant-powercalc/profile_library/signify/LCX028/model.json
{
  "calculation_strategy": "lut",
  "created_at": "2026-04-06T18:05:55Z",
  "device_type": "light",
  "measure_description": "Measured with utils/measure script",
  "measure_device": "TP-Link Kasa KP115",
  "measure_method": "script",
  "measure_settings": {
    "SAMPLE_COUNT": 1,
    "SLEEP_TIME": 2,
    "VERSION": "v1.20.11:docker"
  },
  "name": "Hue Festavia Outdoor White & Colour Gradient Globe String Lights, 14m",
  "standby_power": 0.38
}

=== ggear/homeassistant-powercalc/profile_library/epson/L6270 Series/model.json
{
  "name": "EPSON L6270 Series",
  "calculation_strategy": "fixed",
  "device_type": "printer",
  "measure_method": "manual",
  "measure_device": "Shelly Plus Plug S",
  "measure_description": "Printer was measured while idle and while printing",
  "fixed_config": {
    "states_power": {
      "idle": 1.52,
      "printing": 12
    }
  },
  "created_at": "2024-12-06T12:00:00",
  "author": "Andrzej Dopierala <undefine@aramin.net>"
}

=== ggear/homeassistant-powercalc/profile_library/eq-3/HmIP-FROLL/model.json
{
  "measure_description": "Manually measured with dummy load attached at 7.7W (average over 300s) multiple times, than calculated average of that.",
  "measure_device": "Shelly PM Mini Gen3",
  "measure_method": "script",
  "measure_settings": {
    "VERSION": "v1.17.1:docker"
  },
  "name": "HmIP-FROLL",
  "standby_power": 0.12,
  "standby_power_on": 0.2,
  "sensor_config": {
    "power_sensor_naming": "{} Device Power",
    "energy_sensor_naming": "{} Device Energy"
  },
  "device_type": "cover",
  "calculation_strategy": "fixed",
  "fixed_config": {
    "states_power": {
      "opening": 0,
      "closing": 0
    }
  },
  "sub_profile_select": {
    "matchers": [
      {
        "type": "entity_state",
        "entity_id": "cover.{{source_object_id}}",
        "map": {
          "closing": "closing",
          "opening": "opening"
        }
      }
    ],
    "default": "no_movement"
  },
  "created_at": "2025-02-04T18:37:40",
  "author": "CV",
  "description": "HomematicIP flush mounted shutter actuator. This model is only configured to calculate the power usage of the smart actuator itself because the shutter motor connected is individual and can have different power draw even windows-by-window."
}

=== ggear/homeassistant-powercalc/profile_library/dreo/DR-HTF002S/model.json
{
  "measure_description": "Manually measured",
  "measure_method": "manual",
  "measure_device": "Aqara Smart Plug EU (SP-EUC01)",
  "name": "Dreo smart tower fan",
  "standby_power": 1.04,
  "linear_config": {
    "attribute": "percentage",
    "calibrate": [
      "16 -> 17.76",
      "33 -> 22.39",
      "50 -> 25.75",
      "66 -> 28.61",
      "83 -> 32.19",
      "100 -> 39.62"
    ]
  },
  "device_type": "fan",
  "calculation_strategy": "linear",
  "created_at": "2025-07-14T10:10:08.375127+02:00",
  "author": "miggi92 <miggi92@users.noreply.github.com>"
}

=== ggear/homeassistant-powercalc/profile_library/shelly/Shelly 3EM/model.json
{
  "measure_description": "Manually measured. Transcribed from https://www.youtube.com/watch?v=RlSCe9xaUPE",
  "measure_method": "manual",
  "measure_device": "GW Instek GPM-8310",
  "name": "Shelly 3EM",
  "aliases": [
    "SHEM-3"
  ],
  "discovery_by": "entity",
  "device_type": "smart_switch",
  "calculation_strategy": "fixed",
  "only_self_usage": false,
  "standby_power": 1.22,
  "standby_power_on": 1.22,
  "sensor_config": {
    "power_sensor_naming": "{} Device Power",
    "energy_sensor_naming": "{} Device Energy"
  },
  "created_at": "2024-12-01T18:27:00",
  "author": "RubenKelevra <cyrond@gmail.com>"
}

=== ggear/homeassistant-powercalc/profile_library/shelly/Shelly i3/model.json
{
  "measure_description": "The measured device fw: 1.14.1-rc1, Eco Mode enabled, Wifi Client enabled, LED disabled. The result represents the average value of measurements collected from the measurement device API for the following scenarios: dumb device/baseline consumption (~4.9W) and the measured device",
  "measure_method": "manual",
  "measure_device": "Shelly PM Mini Gen3",
  "measure_device_firmware": "20241011-114503/1.4.4-g6d2a586",
  "measure_settings": {
    "SAMPLE_COUNT": 200,
    "SLEEP_TIME": 0.5
  },
  "name": "Shelly i3",
  "aliases": [
    "SHIX3-1"
  ],
  "discovery_by": "device",
  "device_type": "generic_iot",
  "only_self_usage": true,
  "calculation_strategy": "fixed",
  "standby_power": 0.587,
  "sensor_config": {
    "power_sensor_naming": "{} Device Power",
    "energy_sensor_naming": "{} Device Energy"
  },
  "created_at": "2024-01-09T22:55:00 CET",
  "author": "Michal Bartak <maxym.srpl@gmail.com>"
}

=== ggear/homeassistant-powercalc/profile_library/shelly/shelly pm mini gen3/model.json
{
  "measure_description": "Manually measured. Transcribed from https://www.youtube.com/watch?v=ZXC4vft57gU",
  "measure_method": "manual",
  "measure_device": "GW Instek GPM-8310",
  "name": "Shelly PM Mini Gen3",
  "aliases": [
    "S3PM-001PCEU16"
  ],
  "discovery_by": "device",
  "device_type": "power_meter",
  "only_self_usage": true,
  "calculation_strategy": "fixed",
  "standby_power": 0.642,
  "sensor_config": {
    "power_sensor_naming": "{} Device Power",
    "energy_sensor_naming": "{} Device Energy"
  },
  "created_at": "2024-12-01T16:51:00",
  "author": "RubenKelevra <cyrond@gmail.com>"
}
